In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])

In [5]:
print(a1)
type(a1)

[1 2 3]


numpy.ndarray

In [4]:
a1

array([1, 2, 3])

In [3]:
a2=np.array([[1,2.0,3.3],
            [4,5,6.7]])

a3=np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]],
            [[10,11,12],
            [13,14,15],
            [16,17,18]]])

In [17]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a3.shape


(2, 3, 3)

In [11]:
# no of dimensions
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [12]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [13]:
a1.size,a2.size,a3.size

(3, 6, 18)

In [4]:
# Create a DataFrame from a Numpy array
import pandas as pd
df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.7

## Creating arrays

In [4]:
# shift + tab
ones = np.ones((2,3))

In [5]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
zeros=np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [9]:
random_array=np.random.randint(0,10,size=(3,5))
random_array

array([[9, 7, 7, 3, 8],
       [7, 1, 3, 6, 7],
       [4, 6, 2, 3, 6]])

In [10]:
random_array.shape

(3, 5)

In [11]:
r=np.random.geometric(p=0.35,size=10)
r

array([8, 1, 2, 1, 2, 2, 1, 3, 2, 4])

In [13]:
# Pseudo-random numbers
np.random.seed(seed = 0)
rand_array4=np.random.randint(10,size=(5,3))
rand_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

## Viewing arrays and matrices

In [14]:
np.unique(rand_array4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a3[:2,:3,:2]

array([[[ 1,  2],
        [ 4,  5],
        [ 7,  8]],

       [[10, 11],
        [13, 14],
        [16, 17]]])

In [19]:
a3[:1,:1,:2]

array([[[1, 2]]])

In [20]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [21]:
a3[:1,:2,:2]

array([[[1, 2],
        [4, 5]]])

In [22]:
a4=np.random.randint(10,size=(2,3,4,5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [23]:
# Get first 4 numbers of the inner most arrays
a4[: ,:,:,:4]

array([[[[6, 7, 7, 8],
         [5, 9, 8, 9],
         [3, 0, 3, 5],
         [2, 3, 8, 1]],

        [[3, 3, 7, 0],
         [9, 9, 0, 4],
         [3, 2, 7, 2],
         [0, 4, 5, 5]],

        [[8, 4, 1, 4],
         [8, 1, 1, 7],
         [9, 3, 6, 7],
         [0, 3, 5, 9]]],


       [[[4, 6, 4, 4],
         [4, 4, 8, 4],
         [7, 5, 5, 0],
         [5, 9, 3, 0]],

        [[0, 1, 2, 4],
         [0, 3, 2, 0],
         [5, 9, 0, 2],
         [2, 9, 2, 3]],

        [[2, 3, 4, 1],
         [9, 1, 4, 6],
         [2, 3, 0, 0],
         [0, 6, 3, 3]]]])

## Manipulating & compairing arrays

### Arithmetic

In [4]:
a1

array([1, 2, 3])

In [5]:
ones = np.ones(3)

In [6]:
a1 + ones

array([2., 3., 4.])

In [7]:
a1-ones

array([0., 1., 2.])

In [8]:
a1*ones

array([1., 2., 3.])

In [9]:
a1/ones

array([1., 2., 3.])

In [11]:
a2


array([[1. , 2. , 3.3],
       [4. , 5. , 6.7]])

In [12]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 20.1]])

In [13]:
a2 /a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.23333333]])

In [14]:
# floor division
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [15]:
print(np.add(a1,a2))
print(np.square(a2))

[[2.  4.  6.3]
 [5.  7.  9.7]]
[[ 1.    4.   10.89]
 [16.   25.   44.89]]


### Aggregation
Aggregation = performing the same operation on a number of things

use python's methods sum() on python datatypes and 
Numpy's methods on Numpy arrays

In [16]:
# Creating a massive Numpy array
mass_array= np.random.random(100000)
mass_array[:10]

array([0.28875062, 0.6120848 , 0.21795039, 0.54306412, 0.77936171,
       0.0740976 , 0.03030796, 0.33721678, 0.94527753, 0.50909788])

In [17]:
%timeit sum(mass_array) # Python's sum()
%timeit np.sum(mass_array) # Numpy's sum()

6.16 ms ± 40.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
35.9 µs ± 374 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [2]:
# Demo of std and var
h_arr=np.array([1,100,200,300,4000,5000])
l_arr=np.array([2,4,6,8,10])

In [4]:
np.var(h_arr),np.var(l_arr)

(4296133.472222221, 8.0)

In [5]:
np.std(h_arr),np.std(l_arr)

(2072.711623024829, 2.8284271247461903)

### Reshaping & transposong

In [7]:
a2.shape


(2, 3)

In [8]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [10]:
a2_re=a2.reshape(2,3,1)

In [12]:
# numpy broadcast
a2_re*a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [107.2, 113.9, 120.6]]])

In [13]:
#  transpose
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.7]])

In [14]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.7]])

### Dot Product

In [4]:
np.random.seed(0)
mat1=np.random.randint(10,size=(5,3))
mat2=np.random.randint(10,size=(5,3))

In [5]:
mat1,mat2

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6],
        [8, 8, 1]]),
 array([[6, 7, 7],
        [8, 1, 5],
        [9, 8, 9],
        [4, 3, 0],
        [3, 5, 0]]))

In [6]:
# Element-wise multiplication(Hadamard product)
mat1*mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [7]:
# Dot product
np.dot(mat1,mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [8]:
np.dot(mat1,mat2.reshape(3,5))

array([[ 39,  35,  44,  55,   5],
       [ 80,  84, 104, 132,  31],
       [ 49,  66,  67,  79,  23],
       [ 77,  91, 102, 125,  32],
       [ 91, 128, 123, 141,  40]])

In [9]:
# Transpose mat1
mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

In [11]:
mat1=mat1.T

In [12]:
np.dot(mat1,mat2)

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]])

### Dot product example (nut butter sales)

In [3]:
np.random.seed(0)
# Number of jars sold
sales_amounts=np.random.randint(20,size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [7]:
# Create weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amounts,index=["Mon","Tues","Wed","Thrus","Fri"],
                           columns=["Almond butter","Peanut butter","Cashew butter"])

In [8]:
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thrus              4              6             12
Fri                1              6              7

In [11]:
# Create prices array
prices = np.array([10,8,12])
prices.shape

(3,)

In [12]:
# Create butter_prices DataFrame
butter_prices=pd.DataFrame(prices.reshape(1,3),index=["Price"],
                           columns=["Almond butter","Peanut butter","Cashew butter"])

In [13]:
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [15]:
total_sales=prices.dot(sales_amounts)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [16]:
total_sales=prices.dot(sales_amounts.T)

In [17]:
total_sales

array([240, 138, 458, 232, 142])

In [18]:
# Create daily_sales
butter_prices.shape,weekly_sales.shape

((1, 3), (5, 3))

In [19]:
daily_sales = butter_prices.dot(weekly_sales.T)

In [20]:
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thrus              4              6             12
Fri                1              6              7

In [23]:
weekly_sales["Total ($)"]=daily_sales.T # change the shape

In [24]:
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total ($)
Mon               12             15              0        240
Tues               3              3              7        138
Wed                9             19             18        458
Thrus              4              6             12        232
Fri                1              6              7        142

   ### Comparison Operators

In [27]:
a1>a2

array([[False, False, False],
       [False, False, False]])

In [30]:
(a1>=a2).dtype

dtype('bool')

In [29]:
a1,a2

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.7]]))

In [31]:
a2<5

array([[ True,  True,  True],
       [ True, False, False]])

In [33]:
a2==a1

array([[ True,  True, False],
       [False, False, False]])

## Sorting arrays

In [35]:
random_array=np.random.randint(10,size=(3,5))

In [36]:
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [37]:
np.sort(random_array)

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

In [38]:
np.argsort(random_array)

array([[2, 3, 0, 1, 4],
       [4, 3, 2, 0, 1],
       [2, 3, 0, 4, 1]], dtype=int64)

In [39]:
np.argmin(random_array)

9

In [40]:
np.argmax(random_array,axis=0)

array([1, 1, 1, 0, 0], dtype=int64)

In [41]:
np.argmax(random_array,axis=1)

array([4, 1, 1], dtype=int64)

In [43]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [44]:
np.argmax(a3,axis=0)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [45]:
a3[1][0][0]=0

In [46]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 0, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [47]:
np.argmax(a3,axis=0)

array([[0, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

## Practical Example - Numpy in Action !!!

In [16]:
%%html
<img src="images/panda.png"/>

In [10]:
## Turn an image into a Numpy array
from matplotlib.image import imread
panda= imread("images/panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [11]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [12]:
panda.size,panda.shape,panda.ndim

(24465000, (2330, 3500, 3), 3)

In [17]:
%%html
<img src="images/car-photo.png"/>

In [18]:
car=imread("images/car-photo.png")
print(type(car))

<class 'numpy.ndarray'>


In [20]:
car[:1]


array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]]], dtype=float32)