In [1]:
import numpy as np

## DataTypes & Attributes

In [3]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])

In [5]:
print(a1)
type(a1)

[1 2 3]


numpy.ndarray

In [4]:
a1

array([1, 2, 3])

In [6]:
a2=np.array([[1,2.0,3.3],
            [4,5,6.7]])

a3=np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]],
            [[10,11,12],
            [13,14,15],
            [16,17,18]]])

In [17]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a3.shape


(2, 3, 3)

In [11]:
# no of dimensions
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [12]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [13]:
a1.size,a2.size,a3.size

(3, 6, 18)

In [14]:
# Create a DataFrame from a Numpy array
import pandas as pd
df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.7

## Creating arrays

In [4]:
# shift + tab
ones = np.ones((2,3))

In [5]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
zeros=np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [9]:
random_array=np.random.randint(0,10,size=(3,5))
random_array

array([[9, 7, 7, 3, 8],
       [7, 1, 3, 6, 7],
       [4, 6, 2, 3, 6]])

In [10]:
random_array.shape

(3, 5)

In [11]:
r=np.random.geometric(p=0.35,size=10)
r

array([8, 1, 2, 1, 2, 2, 1, 3, 2, 4])

In [13]:
# Pseudo-random numbers
np.random.seed(seed = 0)
rand_array4=np.random.randint(10,size=(5,3))
rand_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

## Viewing arrays and matrices

In [14]:
np.unique(rand_array4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a3[:2,:3,:2]

array([[[ 1,  2],
        [ 4,  5],
        [ 7,  8]],

       [[10, 11],
        [13, 14],
        [16, 17]]])

In [19]:
a3[:1,:1,:2]

array([[[1, 2]]])

In [20]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [21]:
a3[:1,:2,:2]

array([[[1, 2],
        [4, 5]]])

In [22]:
a4=np.random.randint(10,size=(2,3,4,5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [23]:
# Get first 4 numbers of the inner most arrays
a4[: ,:,:,:4]

array([[[[6, 7, 7, 8],
         [5, 9, 8, 9],
         [3, 0, 3, 5],
         [2, 3, 8, 1]],

        [[3, 3, 7, 0],
         [9, 9, 0, 4],
         [3, 2, 7, 2],
         [0, 4, 5, 5]],

        [[8, 4, 1, 4],
         [8, 1, 1, 7],
         [9, 3, 6, 7],
         [0, 3, 5, 9]]],


       [[[4, 6, 4, 4],
         [4, 4, 8, 4],
         [7, 5, 5, 0],
         [5, 9, 3, 0]],

        [[0, 1, 2, 4],
         [0, 3, 2, 0],
         [5, 9, 0, 2],
         [2, 9, 2, 3]],

        [[2, 3, 4, 1],
         [9, 1, 4, 6],
         [2, 3, 0, 0],
         [0, 6, 3, 3]]]])

## Manipulating & compairing arrays

### Arithmetic

In [4]:
a1

array([1, 2, 3])

In [5]:
ones = np.ones(3)

In [6]:
a1 + ones

array([2., 3., 4.])

In [7]:
a1-ones

array([0., 1., 2.])

In [8]:
a1*ones

array([1., 2., 3.])

In [9]:
a1/ones

array([1., 2., 3.])

In [11]:
a2


array([[1. , 2. , 3.3],
       [4. , 5. , 6.7]])

In [12]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 20.1]])

In [13]:
a2 /a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.23333333]])

In [14]:
# floor division
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [15]:
print(np.add(a1,a2))
print(np.square(a2))

[[2.  4.  6.3]
 [5.  7.  9.7]]
[[ 1.    4.   10.89]
 [16.   25.   44.89]]


### Aggregation
Aggregation = performing the same operation on a number of things

use python's methods sum() on python datatypes and 
Numpy's methods on Numpy arrays

In [16]:
# Creating a massive Numpy array
mass_array= np.random.random(100000)
mass_array[:10]

array([0.28875062, 0.6120848 , 0.21795039, 0.54306412, 0.77936171,
       0.0740976 , 0.03030796, 0.33721678, 0.94527753, 0.50909788])

In [17]:
%timeit sum(mass_array) # Python's sum()
%timeit np.sum(mass_array) # Numpy's sum()

6.16 ms ± 40.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
35.9 µs ± 374 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [2]:
# Demo of std and var
h_arr=np.array([1,100,200,300,4000,5000])
l_arr=np.array([2,4,6,8,10])

In [4]:
np.var(h_arr),np.var(l_arr)

(4296133.472222221, 8.0)

In [5]:
np.std(h_arr),np.std(l_arr)

(2072.711623024829, 2.8284271247461903)

### Reshaping & transposong

In [7]:
a2.shape


(2, 3)

In [8]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [10]:
a2_re=a2.reshape(2,3,1)

In [12]:
# numpy broadcast
a2_re*a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [107.2, 113.9, 120.6]]])

In [13]:
#  transpose
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.7]])

In [14]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.7]])